In [2]:
import numpy as np
data = [[1,2,3,4],[5,6,7,8]]

In [3]:
arr2 = np.array(data)

In [4]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
arr = np.random.randn(2,3)

In [6]:
arr

array([[ 0.31603683, -1.37040612,  1.22329509],
       [-0.21989398,  0.20266245, -0.57082782]])

In [7]:
arr.ndim

2

In [8]:
arr.shape

(2, 3)

In [14]:
x = np.array([[1,2,3,5,2]])
print(x)
print(x.ndim)
print(x.shape)

[[1 2 3 5 2]]
2
(1, 5)


In [21]:
xy = np.arange(45).reshape(9,5).astype('float')
print(xy)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34.]
 [35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44.]]


In [78]:
DDD = np.arange(45).reshape(3,3,5)
#(depth, row , col)
print(DDD)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]]


In [75]:
DDD[1,2:1,3,1:7]

IndexError: too many indices for array

In [31]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
a[0:6:2]
#[start, end , skip]
#(0 to 6 ki slicing with gap of 2 matlab aik value skip hogi)

array([0, 2, 4])

In [60]:
b = np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [62]:
bi=b[4:5,2:3]
print(bi)

[[18]]


In [89]:
bg = np.arange(75).reshape(5,3,5)
print(bg)
print("---------------------------------")

bii = bg[1:3,2:3,3:4]
print(bii)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]

 [[45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]

 [[60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]]]
---------------------------------
[[[28]]

 [[43]]]


In [76]:
bb = np.arange(27).reshape(3,3,3)
#(depth, row , col)
print(bb)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [77]:
bb[1:2,1:3,1:2]

array([[[13],
        [16]]])

In [93]:
div = np.linspace(-1.3,2.5,64)
print(div)

[-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]


In [100]:
divv = np.arange(1,51,9.8)
#linspace formula = (b-a/n-1)
print(divv)

[ 1.  10.8 20.6 30.4 40.2 50. ]


In [102]:
xx = np.arange(1,22,2)
xx

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [117]:
arr1 = np.arange(100).reshape(10,2,5)
print(arr1)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]]

 [[60 61 62 63 64]
  [65 66 67 68 69]]

 [[70 71 72 73 74]
  [75 76 77 78 79]]

 [[80 81 82 83 84]
  [85 86 87 88 89]]

 [[90 91 92 93 94]
  [95 96 97 98 99]]]
